name: twist_chat
description: "A real time twist chat."

publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.3.0
  http: ^1.3.0
  web_socket_channel: ^3.0.2
  flutter_secure_storage: ^9.2.4
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.4
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/google.png