// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLkEfkALkri8C0lJ2bEvbXcATaxMW5rI8',
    appId: '1:1093568117572:web:8fee3561fe32d58731f511',
    messagingSenderId: '1093568117572',
    projectId: 'twistchat-74696',
    authDomain: 'twistchat-74696.firebaseapp.com',
    storageBucket: 'twistchat-74696.firebasestorage.app',
    measurementId: 'G-TVMZ3MLB6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh5WpVk-IgKhRwHPjwXPy3QYeX8EJ1oQU',
    appId: '1:1093568117572:android:26b89b030695c11c31f511',
    messagingSenderId: '1093568117572',
    projectId: 'twistchat-74696',
    storageBucket: 'twistchat-74696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu0mDkEABN_PCZ32iJ0f3_mmvFM8n6uvQ',
    appId: '1:1093568117572:ios:0f706d91f077cab231f511',
    messagingSenderId: '1093568117572',
    projectId: 'twistchat-74696',
    storageBucket: 'twistchat-74696.firebasestorage.app',
    androidClientId: '1093568117572-d8o8l0bsvt8mfng0rgkobh46je9ricpb.apps.googleusercontent.com',
    iosClientId: '1093568117572-ff1qdrapru3upatvav09l5ngmqsl4l67.apps.googleusercontent.com',
    iosBundleId: 'com.shogoshima.twistchat',
  );

}